[package]
name = "image-to-ASCII"
version = "0.1.0"
edition = "2024"

[dependencies]
rusty-api = "0.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
image = "0.24"
termcolor = "1.4"
rusttype = "0.9"