name: Rust Backend CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Run Tests
      run: cargo test --verbose
      working-directory: ./backend

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Build release
      run: cargo build --release --verbose
      working-directory: ./backend
